#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};
#define JIP(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
    jip = 1; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC (HC_Client select 1)

class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 0;

        // Martinez
        F(Martinez_fnc_createLoadout,CLIENT)
        F(Martinez_fnc_loadoutsLoad,CLIENT)
        F(Martinez_fnc_loadLocker,CLIENT)
        F(Martinez_fnc_displayWhitelist,CLIENT)

        F(MartinezSrv_fnc_loadoutServer,SERVER)
        F(MartinezSrv_fnc_lockerServer,SERVER)
        F(MartinezSrv_fnc_whitelistServer,SERVER)

        /* Client only functions */
        F(life_fnc_AAN,CLIENT)
        F(life_fnc_addVehicle2Chain,CLIENT)
        F(life_fnc_adminID,CLIENT)
        F(life_fnc_bountyReceive,CLIENT)
        JIP(life_fnc_copLights,CLIENT)
        F(life_fnc_copSearch,CLIENT)
        JIP(life_fnc_copSiren,CLIENT)
        F(life_fnc_freezePlayer,CLIENT)
        F(PHX_fnc_gangCreated,CLIENT)
        F(PHX_fnc_gangDisband,CLIENT)
        F(life_fnc_garageRefund,CLIENT)
        F(life_fnc_giveDiff,CLIENT)
        F(life_fnc_giveItem,CLIENT)
        F(life_fnc_hideObj,CLIENT)
        F(life_fnc_impoundMenu,CLIENT)
        F(life_fnc_jail,CLIENT)
        F(life_fnc_jailMe,CLIENT)
        F(life_fnc_knockedOut,CLIENT)
        F(life_fnc_licenseCheck,CLIENT)
        F(life_fnc_licensesRead,CLIENT)
        F(life_fnc_lightHouse,CLIENT)
        JIP(life_fnc_mediclights,CLIENT)
        F(life_fnc_medicRequest,CLIENT)
        JIP(life_fnc_medicSiren,CLIENT)
        F(life_fnc_moveIn,CLIENT)
        F(life_fnc_pickupMoney,CLIENT)
        F(life_fnc_receiveItem,CLIENT)
        F(life_fnc_receiveMoney,CLIENT)
        F(life_fnc_restrain,CLIENT)
        F(life_fnc_robPerson,CLIENT)
        F(life_fnc_robReceive,CLIENT)
        F(life_fnc_searchClient,CLIENT)
        F(life_fnc_spikeStripEffect,CLIENT)
        F(life_fnc_tazeSound,CLIENT)
        F(life_fnc_ticketPrompt,CLIENT)
        F(life_fnc_vehicleAnimate,CLIENT)
        F(life_fnc_wantedList,CLIENT)
        F(PHX_fnc_wireTransferClient,CLIENT)
        F(SOCK_fnc_updateRequest,CLIENT)
        F(PHX_fnc_gangNewLeader,CLIENT)
        F(LIFE_fnc_clientGetKey,CLIENT)
        F(LIFE_fnc_playerQuery,CLIENT)
        F(PHX_fnc_onIncapacitated,CLIENT)
        F(PHX_fnc_onRevived,CLIENT)
        F(PHX_fnc_hudUpdate,CLIENT)
        F(PHX_fnc_bloodAdministered,CLIENT)
        F(PHX_fnc_hint,CLIENT)
        F(PHX_fnc_chooseSide,CLIENT)
        F(PHX_fnc_recieveMessage,CLIENT)
        F(PHX_fnc_recieveQuery,CLIENT)
        F(PHX_fnc_changeVisibility,CLIENT)
        F(PHX_fnc_healTarget,CLIENT)
        F(PHX_fnc_handleMoney,CLIENT)
        F(PHX_fnc_setFuel,CLIENT)
        F(PHX_fnc_setAmmo,CLIENT)
        F(PHX_fnc_recieveDispute,CLIENT)
        F(PHX_fnc_notify,CLIENT)
        F(PHX_fnc_RscIDLookup,CLIENT)
        F(PHX_fnc_gangHousing,CLIENT)
        F(PHX_fnc_gangInvite,CLIENT)
        F(PHX_fnc_gangKick,CLIENT)
        F(PHX_fnc_startAlliance,CLIENT)
        F(PHX_fnc_notifyLegislation,CLIENT)
        F(PHX_fnc_setIllegalItems,CLIENT)
        F(PHX_fnc_remoteLicense,CLIENT)
        F(PHX_fnc_jobHandling,CLIENT)
        F(PHX_fnc_openBase,CLIENT)
        F(PHX_fnc_openStorage,CLIENT)
        F(PHX_fnc_panic,CLIENT)
        F(PHX_fnc_handleXP,CLIENT)
        F(life_fnc_handleItem,CLIENT)
        F(PHX_fnc_blindfold,CLIENT)
        F(PHX_fnc_seizeMoneyClient,CLIENT)
        F(PHX_fnc_seizevItemsClient,CLIENT)
        F(PHX_fnc_requestLicense,CLIENT)
        F(PHX_fnc_RscIDCard,CLIENT)
        F(PHX_fnc_breathalyse,CLIENT)
        F(PHX_fnc_increaseProfession,CLIENT)
        F(PHX_fnc_medicalPerformClient,CLIENT)
        F(PHX_fnc_seizeCommunications,CLIENT)
        F(PHX_fnc_forceFeed,CLIENT)
        F(PHX_fnc_robInventory,CLIENT)
        F(PHX_fnc_RCZ_capturedClient,CLIENT)
        F(PHX_fnc_RCZ_client,CLIENT)
        F(PHX_fnc_moveIn,CLIENT)
        F(PHX_fnc_setStat,CLIENT)
        F(PHX_fnc_openMail,CLIENT)
        F(PHX_fnc_robberyMarker,CLIENT)
        F(PHX_fnc_tracker,CLIENT)
        F(PHX_fnc_addActions,ANYONE)

        /* Server only functions */
        F(BIS_fnc_execVM,SERVER)
        F(DB_fnc_updatePartial,SERVER)
        F(DB_fnc_updateRequest,SERVER)
        F(life_fnc_jailSys,SERVER)
        F(life_fnc_wantedAdd,SERVER)
        F(life_fnc_wantedBounty,SERVER)
        F(life_fnc_wantedCrimes,SERVER)
        F(life_fnc_wantedFetch,SERVER)
        F(life_fnc_wantedProfUpdate,SERVER)
        F(life_fnc_wantedRemove,SERVER)
        F(SPY_fnc_cookieJar,SERVER)
        F(SPY_fnc_observe,SERVER)
        F(TON_fnc_addHouse,SERVER)
        F(TON_fnc_chopShopSell,SERVER)
        F(TON_fnc_cleanupRequest,SERVER)
        F(TON_fnc_getVehicles,SERVER)
        F(TON_fnc_insertGang,SERVER)
        F(TON_fnc_keyManagement,SERVER)
        F(TON_fnc_manageSC,SERVER)
        F(TON_fnc_removeGang,SERVER)
        F(TON_fnc_sellHouse,SERVER)
        F(TON_fnc_spawnVehicle,SERVER)
        F(TON_fnc_spikeStrip,SERVER)
        F(TON_fnc_updateGang,SERVER)
        F(TON_fnc_updateHouseTrunk,SERVER)
        F(TON_fnc_vehicleCreate,SERVER)
        F(TON_fnc_vehicleDelete,SERVER)
        F(TON_fnc_vehicleStore,SERVER)
        F(TON_fnc_vehicleUpdate,SERVER)
        F(PHXSRV_fnc_getUndercover,SERVER)
        F(PHXSRV_fnc_prestigeWipe,SERVER)
        F(PHXSRV_fnc_changeOwner,SERVER)
        F(PHXSRV_fnc_sendHook,SERVER)
        F(PHXSRV_fnc_logDispute,SERVER)
        F(PHXSRV_fnc_getID,SERVER)
        F(PHXSRV_fnc_wipeID,SERVER)
        F(PHXSRV_fnc_insertID,SERVER)
        F(PHXSRV_fnc_lookupID,SERVER)
        F(PHXSRV_fnc_addOption,SERVER)
        F(PHXSRV_fnc_addVote,SERVER)
        F(PHXSRV_fnc_saveRewards,SERVER)
        F(PHXSRV_fnc_setLegislation,SERVER)
        F(PHXSRV_fnc_setLegality,SERVER)
        F(PHXSRV_fnc_HandleSO1,SERVER)
        F(PHXSRV_fnc_getBid,SERVER)
        F(PHXSRV_fnc_addBid,SERVER)
        F(PHXSRV_fnc_insertCategory,SERVER)
        F(PHXSRV_fnc_getCategories,SERVER)
        F(PHXSRV_fnc_saveCategory,SERVER)
        F(PHXSRV_fnc_handleChat,SERVER)
        F(PHXSRV_fnc_getHMValue,SERVER)
        F(PHXSRV_fnc_fillArmoury,SERVER)
        F(PHXSRV_fnc_getDestroyerValue,SERVER)
        F(PHXSRV_fnc_getLockupValue,SERVER)
        F(TON_fnc_checkPlate, SERVER)
        F(PHXSRV_fnc_saveStat, SERVER)
        F(PHXSRV_fnc_getMail, SERVER)
        F(PHXSRV_fnc_updateMail, SERVER)
        F(TON_fnc_updateHouse,SERVER)
        F(PHXSRV_fnc_sendMail,SERVER)
        F(PHXSRV_fnc_getPlayerInfo,SERVER)
        F(PHXSRV_fnc_insertCapture,SERVER)

        /* HeadlessClient only functions */
        F(HL_fnc_getPlayerInfo,HC)
        F(HL_fnc_setGlobalVars,HC)
        F(HL_fnc_updatePartial,HC)
        F(HL_fnc_updateRequest,HC)
        F(HL_fnc_getVehicles,HC)
        F(HL_fnc_insertGang,HC)
        F(HL_fnc_removeGang,HC)
        F(HL_fnc_vehicleStore,HC)
        F(HL_fnc_spawnVehicle,HC)
        F(HL_fnc_vehicleCreate,HC)
        F(HL_fnc_vehicleDelete,HC)
        F(HL_fnc_wantedBounty,HC)
        F(HL_fnc_wantedRemove,HC)
        F(HL_fnc_wantedAdd,HC)
        F(HL_fnc_wantedCrimes,HC)
        F(HL_fnc_wantedProfUpdate,HC)
        F(HL_fnc_addHouse,HC)
        F(HL_fnc_sellHouse,HC)
        F(HL_fnc_updateHouse,HC)
        F(HL_fnc_prestigeWipe,HC)
        F(HL_fnc_changeOwner,HC)
        F(HL_fnc_sendHook,HC)
        F(HL_fnc_logDispute,HC)
        F(HL_fnc_getHMValue,HC)
        F(HL_fnc_fillArmoury,HC)
        F(HL_fnc_getDestroyerValue,HC)
        F(HL_fnc_getLockupValue,HC)
        F(HL_fnc_insertID,HC)
        F(HL_fnc_lookupID,HC)
        F(HL_fnc_saveRewards,HC)
        F(HL_fnc_setLegislation,HC)
        F(HL_fnc_setLegality,HC)
        F(HL_fnc_HandleSO1,HC)
        F(HL_fnc_addOption,HC)
        F(HL_fnc_addVote,HC)
        F(HL_fnc_getBid,HC)
        F(HL_fnc_addBid,HC)
        F(HL_fnc_insertCategory,HC)
        F(HL_fnc_getCategories,HC)
        F(HL_fnc_saveCategory,HC)
        F(HL_fnc_insertCapture,HC)
        F(HL_fnc_saveStat,HC)
        F(HL_fnc_updateMail,HC)
        F(HL_fnc_sendMail,HC)
        F(HL_fnc_updateGang,HC)

        /* Functions for everyone */
        F(BIS_fnc_effectKilledAirDestruction,ANYONE)
        F(BIS_fnc_effectKilledSecondaries,ANYONE)
        F(life_fnc_animSync,ANYONE)
        F(life_fnc_broadcast,ANYONE)
        F(life_fnc_colorVehicle,ANYONE)
        F(life_fnc_corpse,ANYONE)
        F(life_fnc_flashbang,ANYONE)
        F(life_fnc_jumpFnc,ANYONE)
        F(life_fnc_lockVehicle,ANYONE)
        F(life_fnc_pulloutVeh,ANYONE)
        F(life_fnc_say3D,ANYONE)
        F(life_fnc_setFuel,ANYONE)
        F(life_fnc_simDisable,ANYONE)
        F(SPY_fnc_notifyAdmins,ANYONE)
        F(PHX_fnc_RCZ_delete,ANYONE)
        F(BIS_fnc_debugConsoleExec,ANYONE) // TODO: REMOVEEEEE
    };

    class Commands {
        mode = 1;
        jip = 0;

        F(addHandgunItem,ANYONE)
        F(addMagazine,ANYONE)
        F(addPrimaryWeaponItem,ANYONE)
        F(addWeapon,ANYONE)
        F(setFuel,ANYONE)
    };
};
